Add DatabindingLaunchConfigurationTab
PalladioSimulator/Palladio-Core-Commons pull request #27
Opened 2021-05-18 10:12 UTC by sdkrach

This PR adds a new bundle for for shared ui components and a common launch configuration tab base implementation, which facilitates the use of eclipse databindings.

A concrete implementation can be found [EDP2Tab](https://github.com/PalladioSimulator/Palladio-QuAL-RecorderFramework/blob/QUAL-47/bundles/org.palladiosimulator.recorderframework.edp2/src/org/palladiosimulator/recorderframework/edp2/launch/EDP2Tab.java).

2021-05-26 17:42 UTC, seiferma requested changes
This adapter is really cool idea. Most of the changes look good to me.

However, we should at least decide about that `.gitignore` change. The remaining stuff is not that important.

2021-05-26 17:42 UTC, seiferma commented on bundles/org.palladiosimulator.commons.ui/src/org/palladiosimulator/commons/ui/launch/ObservableLaunchConfigurationAdapter.java
> + * For detaiuls on its usage, please see {@link ObservableLaunchConfigurationAttributeFactory}.
Typo: details

2021-05-26 17:42 UTC, seiferma commented on bundles/org.palladiosimulator.commons.ui/src/org/palladiosimulator/commons/ui/launch/ObservableLaunchConfigurationAdapter.java
> +    protected Map<String, IObservableValue<?>> observables = new HashMap<>();
Could be final.

2021-05-26 17:42 UTC, seiferma commented on bundles/org.palladiosimulator.commons.ui/src/org/palladiosimulator/commons/ui/launch/ObservableLaunchConfigurationAdapter.java
> +    public void performApply(ILaunchConfigurationWorkingCopy workingCopy) {
After thinking about that for a few moments, the meaning of the method becomes clear. However, some JavaDoc would be appreciated.

2021-05-26 17:42 UTC, seiferma commented on bundles/org.palladiosimulator.commons.ui/src/org/palladiosimulator/commons/ui/launch/AbstractDataBindingLaunchConfigurationTab.java
> + * {@code AbstractLaunchConfigurationTab#initializeFrom(ILaunchConfiguration)},
Using `@link` would generate a link that you can follow with your IDE. Might be better to use it here.

2021-05-28 11:20 UTC, sdkrach commented on .gitignore
> +*.xml_gen
I can get behind that.

2021-05-31 07:30 UTC, seiferma approved these changes
lgtm

2021-05-31 07:30 UTC, merged